# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abderrahim LAKBIR's Blog
email: abderrahim.lakbir@etu.univ-lyon1.fr
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lakabd.github.io" # the base hostname & protocol for your site

github_username:  lakabd
linkedin_username: lakbir-abderrahim

#default author
author: L.Abderrahim

# Build settings
markdown: kramdown

# to activate/deactivate analytics.
# comment this out when developping
production: yes
